[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]

[profile.default.solc]
version = "0.8.20"
optimizer = true
optimizer_runs = 200
